/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_mult_number_matrix_tests.tc" instead.
 */

#include "s21_matrix_tests.h"
START_TEST(s21_mult_num_0) {
  int m1rows = 2, m1cols = 2;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {-59.96198836589801, 72417.36831065716};
  double m1r1[] = {-5386.983329313488, 474416.08804011473};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
  }
  int m1_correctrows = 2, m1_correctcols = 2;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {-3291.924107155526, 3975726.73981227};
  double m1_correctr1[] = {-295746.3681557556, 26045529.83653018};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
  }
  matrix_t M1_result;
  double num = 54.90018254677711;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_1) {
  int m1rows = 1, m1cols = 1;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {1006.7561560739014};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
  }
  int m1_correctrows = 1, m1_correctcols = 1;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {1604836217.3270185};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
  }
  matrix_t M1_result = {0};
  double num = 1594066.4555610772;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_2) {
  int m1rows = 7, m1cols = 7;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {7902.720149287778,  -820.0865926519776,  488.2623663780268,
                   -81986821.52392389, -10586925.448265638, -0.7484386034027316,
                   -86264.65796452147};
  double m1r1[] = {-0.8638642975736871, 1.8503274922673185,  9467.996425034142,
                   44827.941673384965,  -0.7851450448905376, 340034.2775520989,
                   -15.589891754460671};
  double m1r2[] = {-948371258.407546,  5604447591.269553, -17020567.568157963,
                   3145704.524710843,  669082041.3403146, 0.1781819212050081,
                   -0.5821565657253912};
  double m1r3[] = {0.31007016002853494, 3.0226976119728164, -2938.354559697587,
                   537262.3667213455,   -10592650.3015073,  -0.4997921906662959,
                   -61339676.55417505};
  double m1r4[] = {-0.7717962783026426, 7939.858798565601,  -1.3602321931822559,
                   6.832394090331649,   -584466.2646325658, -215.82670054961238,
                   -58.82977083239525};
  double m1r5[] = {14567780.494778259, 63629043.15300304,   -33228542.845398434,
                   -953015.6216825194, -0.7102492181764719, 91306.12630940582,
                   -6576.433349559106};
  double m1r6[] = {-31929.653092517572, -0.9716570146229109, -850.4940475088332,
                   226.57610832425857,  9860207.342697646,   -5108581311.519261,
                   -3787946811.91019};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
    M1.matrix[5][j] = m1r5[j];
    M1.matrix[6][j] = m1r6[j];
  }
  int m1_correctrows = 7, m1_correctcols = 7;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {42767836.86203743,   -4438133.825407553,
                           2642371.846231927,   -443695201340.0304,
                           -57294183760.611015, -4050.3901804575394,
                           -466845940.2701498};
  double m1_correctr1[] = {-4675.0494325551535, 10013.577962489711,
                           51238778.403750904,  242599264.57360908,
                           -4249.0376172490205, 1840193026.5947158,
                           -84369.17095080053};
  double m1_correctr2[] = {-5132383090634.237, 30330075690059.277,
                           -92111683484.05565, 17023882332.608107,
                           3620929382643.072,  964.2825753543831,
                           -3150.5072381123555};
  double m1_correctr3[] = {1678.033609868034,   16358.195141678423,
                           -15901748.521779021, 2907549402.9889755,
                           -57325165446.01469,  -2704.7687975212993,
                           -331957254019.11487};
  double m1_correctr4[] = {-4176.7969379695,    42968823.31525677,
                           -7361.286675165002,  36975.460387368934,
                           -3163006836.2502666, -1168008.0966057626,
                           -318374.1792777112};
  double m1_correctr5[] = {78837722692.07805,   344346818038.39716,
                           -179825790706.16553, -5157517394.661187,
                           -3843.7173682657303, 494129292.28642637,
                           -35590255.4202624};
  double m1_correctr6[] = {-172796476.24183044, -5258.400639556004,
                           -4602692.489277863,  1226181.6000811472,
                           53361340284.37811,   -27646553085547.316,
                           -20499560687145.176};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
    M1_correct.matrix[2][j] = m1_correctr2[j];
    M1_correct.matrix[3][j] = m1_correctr3[j];
    M1_correct.matrix[4][j] = m1_correctr4[j];
    M1_correct.matrix[5][j] = m1_correctr5[j];
    M1_correct.matrix[6][j] = m1_correctr6[j];
  }
  matrix_t M1_result = {0};
  double num = 5411.786834675124;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_3) {
  int m1rows = 8, m1cols = 8;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {72692382.4155844,   -0.4762242416993263, 82786574.12822197,
                   -732.4426112329106, 76151291.03362656,   -8187.09601080357,
                   -409.1072792612277, 0.3435219118652706};
  double m1r1[] = {-44293.43482992287,  -0.3160466668947829,
                   -539.7957536575832,  4418596.318623127,
                   3616108014.080558,   -38103490.149447806,
                   -37264.947833038765, 330932.49306070316};
  double m1r2[] = {-66056.1534314112,  2517336914.037184,  6254589.671788759,
                   -32.6418844454072,  -539333576.7332636, 7.717626437222481,
                   34744368.086131506, -903763742.7260704};
  double m1r3[] = {-508.61380985080075, 1.1325388375394518,  912341336.1062762,
                   -5.602063918763819,  -1395.3088422912897, -724035.816648009,
                   -394739.49554654484, -5587586.132111727};
  double m1r4[] = {783882315.0859796,  -86288.43292801127, 6166.140051752529,
                   -7.970869436532732, -761327.8543573507, -3233.244172260292,
                   9787.532473817362,  755891.8063100356};
  double m1r5[] = {-0.21022566470004056, 894446.5758753284, -470.77444182903906,
                   -75.91509719757683,   948295988.6215394, -426.764724220935,
                   -0.758860477896272,   3.4092580081044623};
  double m1r6[] = {9836.192659139899,  124520138.98636271,
                   32003579.573871754, 0.062342388677512184,
                   -440.1520169403731, -0.005518138289868468,
                   -75106481.21834585, -7159.8537071122955};
  double m1r7[] = {-5.105728300392009, 0.7045131011979258, -1296880.4936237165,
                   -2917.575828583463, -908879.889291471,  0.2245944560927844,
                   68196.44954158032,  -563429184.7284288};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
    M1.matrix[5][j] = m1r5[j];
    M1.matrix[6][j] = m1r6[j];
    M1.matrix[7][j] = m1r7[j];
  }
  int m1_correctrows = 8, m1_correctcols = 8;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {70823856.78493929,  -0.46398310759448297,
                           80658581.75142072,  -713.6154969385809,
                           74193855.68242885,  -7976.650318581228,
                           -398.5913570754223, 0.3346918326234206};
  double m1_correctr1[] = {-43154.89162224728, -0.3079228267075578,
                           -525.9205418746446, 4305018.248975881,
                           3523157552.382082,  -37124056.73984734,
                           -36307.06878386128, 322426.01927694335};
  double m1_correctr2[] = {-64358.20914004407,  2452629878.8769336,
                           6093818.202722146,   -31.8028392017102,
                           -525470245.00433195, 7.519248253339999,
                           33851279.427703016,  -880532894.3040577};
  double m1_correctr3[] = {-495.5401161813175,  1.103427426201394,
                           888890004.4293808,   -5.4580653363968406,
                           -1359.4430438699121, -705424.7953008557,
                           -384592.8909045361,  -5443959.694865538};
  double m1_correctr4[] = {763732965.8904363, -84070.42681517785,
                           6007.642141160223, -7.765981753040133,
                           -741758.257627697, -3150.135056762282,
                           9535.948268149914, 736461.9407979909};
  double m1_correctr5[] = {-0.2048219067042479, 871455.2211180863,
                           -458.67339242634927, -73.96373310476679,
                           923920458.4587334,   -415.79492519986104,
                           -0.739354303990369,  3.321624534583039};
  double m1_correctr6[] = {9583.35766486922,   121319403.7305372,
                           31180941.6753875,   0.06073990507127124,
                           -428.8381034641116, -0.005376296978778726,
                           -73175902.24265997, -6975.812825264123};
  double m1_correctr7[] = {-4.974487806197568, 0.6864039026413604,
                           -1263544.75249522,  -2842.5808286412116,
                           -885517.5325783566, 0.21882135465127495,
                           66443.48988263097,  -548946486.0228097};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
    M1_correct.matrix[2][j] = m1_correctr2[j];
    M1_correct.matrix[3][j] = m1_correctr3[j];
    M1_correct.matrix[4][j] = m1_correctr4[j];
    M1_correct.matrix[5][j] = m1_correctr5[j];
    M1_correct.matrix[6][j] = m1_correctr6[j];
    M1_correct.matrix[7][j] = m1_correctr7[j];
  }
  matrix_t M1_result = {0};
  double num = 0.9742954410276072;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_4) {
  int m1rows = 3, m1cols = 3;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {-769878.6201039073, -0.6897538841731764, 547.1313918801934};
  double m1r1[] = {1318.0710152605823, 4048087.838645975, -7032.532564480634};
  double m1r2[] = {6870100.516796523, -68023623.05026099, 8790281573.457994};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
  }
  int m1_correctrows = 3, m1_correctcols = 3;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {495548.8012260294, 0.4439748052710996,
                           -352.17279487871144};
  double m1_correctr1[] = {-848.4045335029588, -2605638.1140028755,
                           4526.639642806345};
  double m1_correctr2[] = {-4422086.789397211, 43784856.44017309,
                           -5658052298.657744};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
    M1_correct.matrix[2][j] = m1_correctr2[j];
  }
  matrix_t M1_result = {0};
  double num = -0.6436713376442994;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_5) {
  int m1rows = 6, m1cols = 2;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {4.644940309874556, -0.4952186919792394};
  double m1r1[] = {48177.26477614651, -29.32221564073566};
  double m1r2[] = {-310085.81189311243, 413634.39109687286};
  double m1r3[] = {-938843881.7434876, 0.14073477276012702};
  double m1r4[] = {5428214.745248525, 0.1998820648983709};
  double m1r5[] = {5442.771682536617, 0.25173922856166786};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
    M1.matrix[5][j] = m1r5[j];
  }
  int m1_correctrows = 6, m1_correctcols = 2;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {-25.565641953948194, 2.7256720051125285};
  double m1_correctr1[] = {-265166.5294749041, 161.38878357034318};
  double m1_correctr2[] = {1706704.997910455, -2276633.936531171};
  double m1_correctr3[] = {5167374590.429796, -0.7746008712333352};
  double m1_correctr4[] = {-29876765.97934878, -1.1001461726739807};
  double m1_correctr5[] = {-29956.88701898028, -1.3855667788644932};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
    M1_correct.matrix[2][j] = m1_correctr2[j];
    M1_correct.matrix[3][j] = m1_correctr3[j];
    M1_correct.matrix[4][j] = m1_correctr4[j];
    M1_correct.matrix[5][j] = m1_correctr5[j];
  }
  matrix_t M1_result = {0};
  double num = -5.5039764234642305;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_6) {
  int m1rows = 3, m1cols = 3;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {-0.940833935835929, -9.718177715502897, 465162237.9698607};
  double m1r1[] = {-9545951.79742283, -68.71698411288833, 34866.12250020876};
  double m1r2[] = {-9909491.045814412, 6302925.361054401, 44401770.48726141};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
  }
  int m1_correctrows = 3, m1_correctcols = 3;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {-690128755.0578847, -7128562898.055244,
                           3.41209881959511E+17};
  double m1_correctr1[] = {-7002230233058746, -50405884493.33975,
                           25575303779179.3};
  double m1_correctr2[] = {-7268896728973614, 4623377056209635,
                           32569975870942040};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
    M1_correct.matrix[2][j] = m1_correctr2[j];
  }
  matrix_t M1_result = {0};
  double num = 733528765.0362087;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_7) {
  int m1rows = 8, m1cols = 8;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {50.68428470833942,   -5294.67670447269,  -70385079.70856616,
                   -0.9534279373236458, -527497.7387018267, 0.3154321741686382,
                   32391.427152045595,  -86368.30967296755};
  double m1r1[] = {717901.2716325003,   -8.93359321320155,  0.1366080055795793,
                   99.9972973366827,    3.5091436783556818, 23520018.73271854,
                   -1515747.4947611992, 28104.388842885797};
  double m1r2[] = {-79.18540440793457, -0.831340948351316,  434.713254031949,
                   478614.1916195974,  -169819402.21417534, -0.1651878191881292,
                   -57781.33236682581, 0.16854161287552405};
  double m1r3[] = {0.27486426880911774,  0.21470305175117033,
                   338411.3588364146,    -7.7665927539709685,
                   3.348788651285438,    0.3629105197488516,
                   -0.39581963412472965, 6.670050537511996};
  double m1r4[] = {-0.7984364265784163, -97.24085336331561, 80.36837579998324,
                   -55.70666792072142,  2143069856.1880834, -78.22767161657117,
                   749.2397286526972,   856.914626796328};
  double m1r5[] = {0.44131433803446674, 3176.1360902860747, -5.548879120803982,
                   5557107668.247037,   -2888129.705061104, 0.25656153344843924,
                   6.1944478851536955,  848383.4684516301};
  double m1r6[] = {-0.7940333301516891, 3252263491.030681,  0.3359927338996447,
                   3523.4009534284805,  -59.35357303082499, 872.328952920268,
                   3123.684268452398,   9517604.63365553};
  double m1r7[] = {2531583.9669116423, -6396744955.603193, 69975.9703082311,
                   627588.7868860891,  -8231.271598348161, -79.59156410946942,
                   2823986532.7583613, 84.03791276240658};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
    M1.matrix[5][j] = m1r5[j];
    M1.matrix[6][j] = m1r6[j];
    M1.matrix[7][j] = m1r7[j];
  }
  int m1_correctrows = 8, m1_correctcols = 8;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {1801193.6169021644,  -188159662.08333713,
                           -2501310949256.8203, -33882.46129477265,
                           -18745959725.92912,  11209.67617373992,
                           1151110885.0474985,  -3069315251.872979};
  double m1_correctr1[] = {25512428467.154587, -317477.7184725969,
                           4854.709286785851,  3553655.629289472,
                           124706.25225587642, 835843059728.9562,
                           -53865901987.36904, 998760189.3178779};
  double m1_correctr2[] = {-2814052.6356865144, -29543.7928789277,
                           15448629.547617607,  17008759852.581385,
                           -6034959851055.881,  -5870.364891677987,
                           -2053405066.9576652, 5989.550391027619};
  double m1_correctr3[] = {9767.993557419271,   7630.013298382273,
                           12026299333.825766,  -276005.42010272044,
                           119007.63279504828,  12896.938675169373,
                           -14066.446878606283, 237037.03271567932};
  double m1_correctr4[] = {-28374.44788519607, -3455698.4554090966,
                           2856092.5013489644, -1979676.64444878,
                           76159380915684.31,  -2780017.190569188,
                           26626119.40850181,  30452617.905085858};
  double m1_correctr5[] = {15683.215680940579,  112871989.5162018,
                           -197193.38471219162, 197485806854796.47,
                           -102636957776.49316, 9117.55979292581,
                           220135.29549004658,  30149441722.494427};
  double m1_correctr6[] = {-28217.972772169156, 115577368295474.12,
                           11940.347409617716,  125212920.4076185,
                           -2109278.595893221,  31000404.777941156,
                           111007982.01909761,  338232034110.5286};
  double m1_correctr7[] = {89966207634.03699,   -227324431020091.66,
                           2486772217.08888,    22302947027.535004,
                           -292518952.31922543, -2828486.542883928,
                           100357468716237.25,  2986498.7326243552};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
    M1_correct.matrix[2][j] = m1_correctr2[j];
    M1_correct.matrix[3][j] = m1_correctr3[j];
    M1_correct.matrix[4][j] = m1_correctr4[j];
    M1_correct.matrix[5][j] = m1_correctr5[j];
    M1_correct.matrix[6][j] = m1_correctr6[j];
    M1_correct.matrix[7][j] = m1_correctr7[j];
  }
  matrix_t M1_result = {0};
  double num = 35537.51675232386;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_8) {
  int m1rows = 4, m1cols = 4;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {702364573.4294152, 304.9136680416351, -8759878.935249496,
                   69.55289429350945};
  double m1r1[] = {-0.14849113996574792, 6236.086686042884, 354.25861813512216,
                   -9381983.714453233};
  double m1r2[] = {38.5612631391928, 340.25364015521467, 73.92843230119807,
                   996.3727741638985};
  double m1r3[] = {22213514.145406954, -834523.0578232043, -963666204.7831101,
                   -764706.8676102406};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
  }
  int m1_correctrows = 4, m1_correctcols = 4;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {145900656.35789937, 63.3390492384223,
                           -1819670.488259726, 14.448070578882117};
  double m1_correctr1[] = {-0.030845739668435262, 1295.4086453363104,
                           73.58936777518299, -1948898.953138063};
  double m1_correctr2[] = {8.010246835952216, 70.68014433646441,
                           15.356991517368005, 206.9743367292187};
  double m1_correctr3[] = {4614364.699526037, -173353.64921340646,
                           -200180272.62007302, -158850.8847491577};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
    M1_correct.matrix[2][j] = m1_correctr2[j];
    M1_correct.matrix[3][j] = m1_correctr3[j];
  }
  matrix_t M1_result = {0};
  double num = 0.20772781241729554;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_9) {
  int m1rows = 2, m1cols = 2;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {7.411262661127413, -791686176.9011146};
  double m1r1[] = {-43304252.822155446, 441944296.6205067};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
  }
  int m1_correctrows = 2, m1_correctcols = 2;
  matrix_t M1_correct = {0};
  s21_create_matrix(m1_correctrows, m1_correctcols, &M1_correct);
  double m1_correctr0[] = {-483.8628674317369, 51687217303.82847};
  double m1_correctr1[] = {2827226735.9270153, -28853441631.41166};

  for (int j = 0; j < m1_correctcols; j++) {
    M1_correct.matrix[0][j] = m1_correctr0[j];
    M1_correct.matrix[1][j] = m1_correctr1[j];
  }
  matrix_t M1_result = {0};
  double num = -65.28750761589266;
  int res = s21_mult_number(&M1, num, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_correct), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_correct);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_mult_num_10) {
  ck_assert_int_eq(s21_mult_number(NULL, 1.0, NULL), S21_ERROR);
}
END_TEST

START_TEST(s21_mult_num_11) {
  INV_MATRIX
  matrix_t M1_result = {0};
  ck_assert_int_eq(s21_mult_number(&inv_matrix, 1.0, &M1_result), S21_ERROR);
}
END_TEST

Suite *s21_mult_number_matrix_tests(void) {
  Suite *s1 = suite_create(PRE_TEST_HEADER "S21_MULT_NUM" POST_TEST_HEADER);
  TCase *tc1_1 = tcase_create("S21_MULT_NUM");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_mult_num_0);
  tcase_add_test(tc1_1, s21_mult_num_1);
  tcase_add_test(tc1_1, s21_mult_num_2);
  tcase_add_test(tc1_1, s21_mult_num_3);
  tcase_add_test(tc1_1, s21_mult_num_4);
  tcase_add_test(tc1_1, s21_mult_num_5);
  tcase_add_test(tc1_1, s21_mult_num_6);
  tcase_add_test(tc1_1, s21_mult_num_7);
  tcase_add_test(tc1_1, s21_mult_num_8);
  tcase_add_test(tc1_1, s21_mult_num_9);
  tcase_add_test(tc1_1, s21_mult_num_10);
  tcase_add_test(tc1_1, s21_mult_num_11);

  return s1;
}
