/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_inverse_matrix_tests.tc" instead.
 */

#include "s21_matrix_tests.h"

START_TEST(s21_inverse_1) {
  int m1rows = 3, m1cols = 3;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {0.392522527906623, 0.6158317981422524, 0.37692040317489217};
  double m1r1[] = {0.7796678028312694, 0.5331794497328695, 0.1878116956340795};
  double m1r2[] = {0.27527358660058154, 0.995069323959477, 0.7594552834750529};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
  }
  int m1_invrows = 3, m1_invcols = 3;
  matrix_t M1_inv;
  s21_create_matrix(m1_invrows, m1_invcols, &M1_inv);
  double m1_invr0[] = {-21.543220252216532, 9.152673041276705,
                       8.428541296591982};
  double m1_invr1[] = {53.39589565718514, -19.20223924353347,
                       -21.751902667794212};
  double m1_invr2[] = {-62.15288683234581, 21.842062921221608,
                       26.761939421832956};

  for (int j = 0; j < m1_invcols; j++) {
    M1_inv.matrix[0][j] = m1_invr0[j];
    M1_inv.matrix[1][j] = m1_invr1[j];
    M1_inv.matrix[2][j] = m1_invr2[j];
  }
  matrix_t M1_result = {0};
  int res = s21_inverse_matrix(&M1, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_inv), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_inv);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_inverse_2) {
  int m1rows = 3, m1cols = 3;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {0.1218298727102286, 0.8843129151454282, 0.7606904468042972};
  double m1r1[] = {0.22941308818372652, 0.8983369054714275, 0.4470249371238503};
  double m1r2[] = {0.9933304026121619, 0.6021466731400157, 0.11433595969821808};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
  }
  int m1_invrows = 3, m1_invcols = 3;
  matrix_t M1_inv = {0};
  s21_create_matrix(m1_invrows, m1_invcols, &M1_inv);
  double m1_invr0[] = {0.7414178623476854, -1.589792051123062,
                       1.2829490136130974};
  double m1_invr1[] = {-1.860926566840905, 3.303451148973593,
                       -0.5347047483818737};
  double m1_invr2[] = {3.3592042126133754, -3.5856902946843836,
                       0.4161282701673231};

  for (int j = 0; j < m1_invcols; j++) {
    M1_inv.matrix[0][j] = m1_invr0[j];
    M1_inv.matrix[1][j] = m1_invr1[j];
    M1_inv.matrix[2][j] = m1_invr2[j];
  }
  matrix_t M1_result = {0};
  int res = s21_inverse_matrix(&M1, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_inv), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_inv);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_inverse_3) {
  int m1rows = 5, m1cols = 5;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {0.9449202699249958, 0.21680057898609262, 0.27487122238906647,
                   0.2529298651525199, 0.5672207919214909};
  double m1r1[] = {0.4985961149605276, 0.516871870743775, 0.03043572904836711,
                   0.6058944615517939, 0.4938671423115971};
  double m1r2[] = {0.6663863247870461, 0.5735605341763624, 0.5369115624014001,
                   0.9481633496695653, 0.18191852814072784};
  double m1r3[] = {0.4344389423260937, 0.5656979712486659, 0.56854273167115,
                   0.2938185623112711, 0.47031928859085215};
  double m1r4[] = {0.41796440869652407, 0.8553933004317102, 0.9627579972969258,
                   0.6958956197065413, 0.6457084231133039};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
  }
  int m1_invrows = 5, m1_invcols = 5;
  matrix_t M1_inv = {0};
  s21_create_matrix(m1_invrows, m1_invcols, &M1_inv);
  double m1_invr0[] = {0.4420760980610289, -0.45704455951310224,
                       0.9364944123095815, 2.4043198002447497,
                       -2.0538668531177198};
  double m1_invr1[] = {-2.427122807159965, 0.9456498223719237,
                       0.6549086724782268, 6.7213640187016965,
                       -3.6713753997570104};
  double m1_invr2[] = {0.6391252937398793, -1.6639662816352057,
                       0.1419119669963243, -1.1492433378531677,
                       1.5083402588760935};
  double m1_invr3[] = {0.5249890645602862, 0.5030172545692994,
                       0.30674909862979055, -4.319962360788367,
                       2.21423450826746};
  double m1_invr4[] = {1.4104073956624494, 0.981983747681965,
                       -2.015953351000205, -4.09107835967503, 3.10646470007475};

  for (int j = 0; j < m1_invcols; j++) {
    M1_inv.matrix[0][j] = m1_invr0[j];
    M1_inv.matrix[1][j] = m1_invr1[j];
    M1_inv.matrix[2][j] = m1_invr2[j];
    M1_inv.matrix[3][j] = m1_invr3[j];
    M1_inv.matrix[4][j] = m1_invr4[j];
  }
  matrix_t M1_result = {0};
  int res = s21_inverse_matrix(&M1, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_inv), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_inv);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_inverse_4) {
  int m1rows = 7, m1cols = 7;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {0.803364447422804,   0.9276635428126416,
                   0.11573605494917416, 0.4700316840128058,
                   0.8634637196302342,  0.026656061123744967,
                   0.022033181430467952};
  double m1r1[] = {0.1119041349058455, 0.874031496091031,   0.33465712679399984,
                   0.0918142026752059, 0.22221159767989418, 0.28060162686440504,
                   0.21501828854023242};
  double m1r2[] = {0.9811539415125439,  0.1864057960419937, 0.595279217262423,
                   0.31426421763412593, 0.8791668283165757, 0.2462622558621652,
                   0.7949243522353054};
  double m1r3[] = {0.57278320577958,     0.5929993946927323,
                   0.028579578445467324, 0.3669073310450506,
                   0.25662277740207784,  0.24348716512764756,
                   0.44589751727043314};
  double m1r4[] = {0.7262159430230344,  0.5775015807719999,  0.0497340255494888,
                   0.20497850745968227, 0.40145169716948603, 0.737920877137581,
                   0.36418994860435827};
  double m1r5[] = {0.5247882097718117, 0.36829388114015393, 0.6640398921459306,
                   0.9019295681367107, 0.8741038462084987,  0.6299156891544223,
                   0.9100017597493675};
  double m1r6[] = {0.8309615635998882,   0.3495844582916987,
                   0.9986805832976463,   0.22428379189826175,
                   0.055800132106001876, 0.430911957393702,
                   0.9430558612489507};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
    M1.matrix[5][j] = m1r5[j];
    M1.matrix[6][j] = m1r6[j];
  }
  int m1_invrows = 7, m1_invcols = 7;
  matrix_t M1_inv = {0};
  s21_create_matrix(m1_invrows, m1_invcols, &M1_inv);
  double m1_invr0[] = {0.8101156161520406,  -1.221802015763796,
                       -0.2550423628005044, -0.024063564254905773,
                       0.5062908826894557,  -0.5084576918220213,
                       0.7811212428168655};
  double m1_invr1[] = {0.01825601418832422,  1.0269436575867013,
                       -0.06696678048694178, 0.6915420606415468,
                       -0.2870925513598174,  -0.2746701266033758,
                       -0.1291872030117056};
  double m1_invr2[] = {0.7992576076489019,   0.06363155731182539,
                       -0.5498477031212776,  -1.8580812518141114,
                       -0.13354257602141423, 0.28486591814841994,
                       1.085529955359519};
  double m1_invr3[] = {0.9820736259602644,   -1.3855121102737473,
                       -1.695105888555286,   0.3413333137174926,
                       -0.37662129290826246, 1.119873981530296,
                       0.625231154644746};
  double m1_invr4[] = {-0.2077754000546547, 0.7579207110502699,
                       1.2875448580273747,  -0.6768298245885611,
                       0.03256294268283266, 0.11266539442486034,
                       -1.0545268094619706};
  double m1_invr5[] = {-0.18413965682465372, -0.10808489772715058,
                       -0.5952828739345424,  -1.2313391758895147,
                       1.590830103829566,    0.43388217338853285,
                       0.07990562875103069};
  double m1_invr6[] = {-1.7041210386356127, 0.9625625761718032,
                       1.4307925311465917,  2.254037893477872,
                       -0.837525647154693,  -0.22308561712630415,
                       -0.8523740562317244};

  for (int j = 0; j < m1_invcols; j++) {
    M1_inv.matrix[0][j] = m1_invr0[j];
    M1_inv.matrix[1][j] = m1_invr1[j];
    M1_inv.matrix[2][j] = m1_invr2[j];
    M1_inv.matrix[3][j] = m1_invr3[j];
    M1_inv.matrix[4][j] = m1_invr4[j];
    M1_inv.matrix[5][j] = m1_invr5[j];
    M1_inv.matrix[6][j] = m1_invr6[j];
  }
  matrix_t M1_result = {0};
  int res = s21_inverse_matrix(&M1, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_inv), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_inv);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_inverse_5) {
  int m1rows = 8, m1cols = 8;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {0.9217223875302487, 0.33646816889606257, 0.7509150831940272,
                   0.2774590933667471, 0.2786158826817444,  0.22352226961075328,
                   0.8900642338196998, 0.782838313096592};
  double m1r1[] = {0.11472324862314864, 0.06091218120249964, 0.4344718462913124,
                   0.5663053393687295,  0.33513061565458435, 0.2619234417640909,
                   0.25006149172911674, 0.632208667558708};
  double m1r2[] = {0.45247749329413645, 0.7489366675553961,
                   0.16447594642007557, 0.89069203963076,
                   0.11785331841102942, 0.8395745518947152,
                   0.05705860783661554, 0.8869725162719537};
  double m1r3[] = {0.45209377849014,    0.23499673971517787,
                   0.5660352237399611,  0.31803830322795634,
                   0.5840481431134317,  0.23258535735067065,
                   0.34180305666930777, 0.0477985061516899};
  double m1r4[] = {0.6827615623925455, 0.7986214584047835, 0.7507929601818346,
                   0.5383254617519082, 0.6153157631744403, 0.1993314657310148,
                   0.7397479356057447, 0.06638674157285007};
  double m1r5[] = {0.2964787984030196, 0.20589711649930975,
                   0.25707594293298,   0.015061970011114312,
                   0.8878107914073641, 0.4708385780253521,
                   0.6219699797563243, 0.623090738743874};
  double m1r6[] = {0.5105459163947182,  0.4030350494378706, 0.05256074470172645,
                   0.14772531989471127, 0.8936432016708725, 0.4116772123328788,
                   0.8583980472121819,  0.9175479574149813};
  double m1r7[] = {0.2965933786600702,  0.47360342762468144,
                   0.07673925152136685, 0.970061977933997,
                   0.6329497705043322,  0.6710417226426213,
                   0.05856810364976628, 0.27921108688687013};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
    M1.matrix[5][j] = m1r5[j];
    M1.matrix[6][j] = m1r6[j];
    M1.matrix[7][j] = m1r7[j];
  }
  int m1_invrows = 8, m1_invcols = 8;
  matrix_t M1_inv = {0};
  s21_create_matrix(m1_invrows, m1_invcols, &M1_inv);
  double m1_invr0[] = {0.28776176721913366, -1.2454366236322505,
                       0.5344336459881864,  3.781324086385832,
                       -1.7060064484977981, -2.7072573593180382,
                       1.9822386247650245,  -0.3987682284886528};
  double m1_invr1[] = {-1.9646492260264008, 0.0778028482964961,
                       1.5382186414687897,  1.375639016495569,
                       1.0747817372860813,  -1.2016196742946108,
                       1.4553255155806115,  -2.146262263038157};
  double m1_invr2[] = {-0.44699294937217077, 0.8398940540491919,
                       0.6040050370013786,   1.087011692467936,
                       0.30721876816503046,  0.6797511595151411,
                       -0.9217929594539764,  -1.3140995188444247};
  double m1_invr3[] = {0.6822380550437575,   0.7496508889278953,
                       -1.001518805467734,   -1.5192890138443174,
                       0.2834474801796214,   -0.5669193759203643,
                       -0.20362346467538747, 1.6982881303378743};
  double m1_invr4[] = {-1.8873271209552342, 0.4865557044105001,
                       0.4954300775772951,  3.771356605718032,
                       -0.7041478354197502, -1.95189164252297,
                       2.395787673963881,   -1.3793479101617916};
  double m1_invr5[] = {2.3902517940828942,  -1.567533496101407,
                       -0.7041553394897527, -4.54310117250627,
                       0.37031024451269984, 5.113883855179924,
                       -4.378051669571197,  2.749254977571716};
  double m1_invr6[] = {2.8537522408458003,  -0.4141267652085742,
                       -2.3683960966640205, -7.109052969605507,
                       1.8013795533470358,  3.9433223713253795,
                       -3.3252341523570474, 3.376365689115268};
  double m1_invr7[] = {-1.2854403254541669, 1.1068671168252642,
                       1.2027353465062907,  2.4900869802786687,
                       -0.7516687823181422, -1.9959946594166627,
                       2.1750347386482,     -2.082319666613886};

  for (int j = 0; j < m1_invcols; j++) {
    M1_inv.matrix[0][j] = m1_invr0[j];
    M1_inv.matrix[1][j] = m1_invr1[j];
    M1_inv.matrix[2][j] = m1_invr2[j];
    M1_inv.matrix[3][j] = m1_invr3[j];
    M1_inv.matrix[4][j] = m1_invr4[j];
    M1_inv.matrix[5][j] = m1_invr5[j];
    M1_inv.matrix[6][j] = m1_invr6[j];
    M1_inv.matrix[7][j] = m1_invr7[j];
  }
  matrix_t M1_result = {0};
  int res = s21_inverse_matrix(&M1, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_inv), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_inv);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_inverse_6) {
  int m1rows = 5, m1cols = 5;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {0.8188269309459919, 0.487400117576538, 0.26953656693924155,
                   0.6866842518116132, 0.1916651510892602};
  double m1r1[] = {0.6179111679399223, 0.6912839435004519, 0.9193536752413889,
                   0.02292410251187693, 0.4428169055580041};
  double m1r2[] = {0.9784921132620453, 0.11260739118843521, 0.876910619435387,
                   0.22233048166557046, 0.44311439988858414};
  double m1r3[] = {0.27688734807794146, 0.1862903218519698, 0.07737925209221153,
                   0.057261345805574515, 0.15164968298372195};
  double m1r4[] = {0.647022547118953, 0.3284821254146263, 0.4881294732114232,
                   0.5474226782605836, 0.08245436750191892};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
  }
  int m1_invrows = 5, m1_invcols = 5;
  matrix_t M1_inv = {0};
  s21_create_matrix(m1_invrows, m1_invcols, &M1_inv);
  double m1_invr0[] = {-7.94604074645906, -2.776581643483504,
                       -0.9635403481441385, 16.19116886446981,
                       8.781455625315878};
  double m1_invr1[] = {-2.0115738097600584, 0.5032783199783444,
                       -1.8795283779846552, 5.07794950501182,
                       2.7344228493926157};
  double m1_invr2[] = {0.014654751512377157, 0.916704598044727,
                       0.42325756762790945, -4.037324001767198,
                       0.19363781200186103};
  double m1_invr3[] = {8.51361740594732, 1.6565494441630826, 1.3879673734588718,
                       -15.369336136194654, -7.878118065862802};
  double m1_invr4[] = {13.757099107352015, 3.3580965749751797,
                       3.3280771481643923, -21.3427988117975,
                       -16.516634456284265};

  for (int j = 0; j < m1_invcols; j++) {
    M1_inv.matrix[0][j] = m1_invr0[j];
    M1_inv.matrix[1][j] = m1_invr1[j];
    M1_inv.matrix[2][j] = m1_invr2[j];
    M1_inv.matrix[3][j] = m1_invr3[j];
    M1_inv.matrix[4][j] = m1_invr4[j];
  }
  matrix_t M1_result = {0};
  int res = s21_inverse_matrix(&M1, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_inv), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_inv);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_inverse_7) {
  int m1rows = 6, m1cols = 6;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {0.00870465919024943, 0.08766145022692096,
                   0.10048788782494844, 0.8702443516808455,
                   0.5901599004830451,  0.04954564368738168};
  double m1r1[] = {0.872764541348794,  0.16535324990257305,
                   0.6212294221464774, 0.09969560440107816,
                   0.3160813720057526, 0.22485685241311137};
  double m1r2[] = {0.9252501191030591, 0.2804411689916322, 0.15632605078398065,
                   0.4802084655081491, 0.7896529775345311, 0.856585945066695};
  double m1r3[] = {0.15818045117597912, 0.6845098474638927,
                   0.15843503726431296, 0.9988726818673033,
                   0.31689846220427176, 0.9166660162431999};
  double m1r4[] = {0.6700282453220456, 0.30496989837170085, 0.7435014137490102,
                   0.5979148335510357, 0.694112003022854,   0.8055861682948534};
  double m1r5[] = {0.34073386956571905,  0.6453536989088298,
                   0.048531672673368886, 0.8780927466865787,
                   0.399106572612702,    0.917100066252921};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
    M1.matrix[1][j] = m1r1[j];
    M1.matrix[2][j] = m1r2[j];
    M1.matrix[3][j] = m1r3[j];
    M1.matrix[4][j] = m1r4[j];
    M1.matrix[5][j] = m1r5[j];
  }
  int m1_invrows = 6, m1_invcols = 6;
  matrix_t M1_inv = {0};
  s21_create_matrix(m1_invrows, m1_invcols, &M1_inv);
  double m1_invr0[] = {-0.19418591248929656, 2.0294921578922627,
                       4.582173299523035,    10.276521150025898,
                       -4.074777949992686,   -11.459275529013775};
  double m1_invr1[] = {0.734900756047274,   -0.8036945480386998,
                       -12.993790674464858, -31.366260303804193,
                       7.573491125904595,   36.992570373777276};
  double m1_invr2[] = {-0.10965405768920962, 0.14969736772052222,
                       -1.4966520194348292,  -0.8938691266072017,
                       1.6891833436889918,   0.7767747780294975};
  double m1_invr3[] = {0.3650222991361143, 1.635254847605976,
                       6.834685726505162,  18.66013168482288,
                       -5.481752825767012, -20.640456010391063};
  double m1_invr4[] = {1.177815841877545,  -2.2828461270321263,
                       -8.347996910412034, -23.760949233936675,
                       6.8690158929255265, 26.00916315959471};
  double m1_invr5[] = {-1.30125493391378,  -0.7686413768102919,
                       4.6092862594588615, 10.7752461748667,
                       -1.645541851647514, -12.280688528187904};

  for (int j = 0; j < m1_invcols; j++) {
    M1_inv.matrix[0][j] = m1_invr0[j];
    M1_inv.matrix[1][j] = m1_invr1[j];
    M1_inv.matrix[2][j] = m1_invr2[j];
    M1_inv.matrix[3][j] = m1_invr3[j];
    M1_inv.matrix[4][j] = m1_invr4[j];
    M1_inv.matrix[5][j] = m1_invr5[j];
  }
  matrix_t M1_result = {0};
  int res = s21_inverse_matrix(&M1, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_inv), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_inv);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_inverse_8) {
  int m1rows = 1, m1cols = 1;
  matrix_t M1 = {0};
  s21_create_matrix(m1rows, m1cols, &M1);
  double m1r0[] = {0.9493646598211576};

  for (int j = 0; j < m1cols; j++) {
    M1.matrix[0][j] = m1r0[j];
  }
  int m1_invrows = 1, m1_invcols = 1;
  matrix_t M1_inv = {0};
  s21_create_matrix(m1_invrows, m1_invcols, &M1_inv);
  double m1_invr0[] = {1.0533360281057662};

  for (int j = 0; j < m1_invcols; j++) {
    M1_inv.matrix[0][j] = m1_invr0[j];
  }
  matrix_t M1_result = {0};
  int res = s21_inverse_matrix(&M1, &M1_result);
  ck_assert_int_eq(s21_eq_matrix(&M1_result, &M1_inv), S21_SUCCESS);
  ck_assert_int_eq(res, S21_OK);
  s21_remove_matrix(&M1_inv);
  s21_remove_matrix(&M1);
  s21_remove_matrix(&M1_result);
}
END_TEST

START_TEST(s21_inverse_9) {
  matrix_t M1 = {0};
  matrix_t M1_result = {0};
  s21_create_matrix(1, 1, &M1);
  ck_assert_int_eq(s21_inverse_matrix(&M1, &M1_result), S21_CALC_ERROR);
  s21_remove_matrix(&M1);
}
END_TEST

START_TEST(s21_inverse_10) {
  matrix_t M1 = {0};
  matrix_t M1_result = {0};
  s21_create_matrix(1, 2, &M1);
  ck_assert_int_eq(s21_inverse_matrix(&M1, &M1_result), S21_CALC_ERROR);
  s21_remove_matrix(&M1);
}
END_TEST

START_TEST(s21_inverse_11) {
  ck_assert_int_eq(s21_inverse_matrix(NULL, NULL), S21_ERROR);
}
END_TEST

START_TEST(s21_inverse_12) {
  INV_MATRIX
  matrix_t M1_result = {0};
  ck_assert_int_eq(s21_inverse_matrix(&inv_matrix, &M1_result), S21_ERROR);
}
END_TEST

START_TEST(s21_calc_comp_13) {
  matrix_t M1 = {0};
  matrix_t M1_result = {0};
  s21_create_matrix(1, 2, &M1);
  ck_assert_int_eq(s21_calc_complements(&M1, &M1_result), S21_CALC_ERROR);
  s21_remove_matrix(&M1);
}
END_TEST

START_TEST(s21_minor_14) {
  matrix_t M1 = {0};
  matrix_t M1_result = {0};
  s21_create_matrix(1, 2, &M1);
  ck_assert_int_eq(s21_minor_matrix(&M1, &M1_result, 1, 2), S21_CALC_ERROR);
  s21_remove_matrix(&M1);
}
END_TEST

Suite *s21_inverse_matrix_tests(void) {
  Suite *s1 = suite_create(PRE_TEST_HEADER "S21_INVERSE" POST_TEST_HEADER);
  TCase *tc1_1 = tcase_create("S21_INVERSE");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_inverse_1);
  tcase_add_test(tc1_1, s21_inverse_2);
  tcase_add_test(tc1_1, s21_inverse_3);
  tcase_add_test(tc1_1, s21_inverse_4);
  tcase_add_test(tc1_1, s21_inverse_5);
  tcase_add_test(tc1_1, s21_inverse_6);
  tcase_add_test(tc1_1, s21_inverse_7);
  tcase_add_test(tc1_1, s21_inverse_8);
  tcase_add_test(tc1_1, s21_inverse_9);
  tcase_add_test(tc1_1, s21_inverse_10);
  tcase_add_test(tc1_1, s21_inverse_11);
  tcase_add_test(tc1_1, s21_inverse_12);
  tcase_add_test(tc1_1, s21_calc_comp_13);
  tcase_add_test(tc1_1, s21_minor_14);

  return s1;
}
