/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "out.tc" instead.
 */

#include "scp_matrix_tests.h"

START_TEST(scp_determinant_0) {
  int rows = 3, cols = 9;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.793926420168389,   0.024674707048111255, 0.7080368048034479,
                 0.00947754662233169, 0.9716562084150235,   0.6704737417382571,
                 0.31996147843358846, 0.4584615662699011,   0.8871917587936811};
  double r1[] = {0.6913843155018434, 0.7954281929679401, 0.24981989015058292,
                 0.7797359279540067, 0.3935525941396727, 0.9992816034449232,
                 0.3568147825875897, 0.7516376249774246, 0.21052497898730105};
  double r2[] = {
      0.8959494499969132,   0.623895518577513,   0.023759297839050064,
      0.047862325586623955, 0.14529103619839767, 0.5727872075778395,
      0.07059611265588861,  0.6431273255102197,  0.4086379649515032};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
    M1.matrix[1][j] = r1[j];
    M1.matrix[2][j] = r2[j];
  }

  double det = 0;
  double correct_det = 0;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_CALC_ERROR);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_1) {
  int rows = 9, cols = 9;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.3704703182351474, 0.5824448570885606,  0.8441609891354462,
                 0.4728118472090358, 0.9043061105084269,  0.937783491861028,
                 0.4352506763542444, 0.48135517135025785, 0.02382905036763705};
  double r1[] = {0.7904201190434834,  0.01199424673211491, 0.8729229719770697,
                 0.3287985735559227,  0.7099044647599662,  0.028047196393755414,
                 0.18032142217694325, 0.4118743110055003,  0.8719659874689129};
  double r2[] = {0.6738170333803952,  0.48144365849905324, 0.2630611745253091,
                 0.29062221796414534, 0.9450871383037022,  0.4523076909056134,
                 0.43323392475117684, 0.32804994276290467, 0.9741319202776118};
  double r3[] = {0.8340392527402305,  0.8165204280992023,  0.9458910608912515,
                 0.18436439185190145, 0.07089718786719645, 0.8288765650867496,
                 0.08223166133049842, 0.9312440299055769,  0.800964627844393};
  double r4[] = {0.8837886658247937, 0.507133722244318,  0.8766215659248748,
                 0.94463212390696,   0.5650814249040501, 0.9109851348248073,
                 0.3714868831417282, 0.7030270096701692, 0.670663600212668};
  double r5[] = {0.4338631875279382,  0.4380957325655963, 0.810725680039834,
                 0.02032818829184657, 0.7015147122697384, 0.16175728768979436,
                 0.3881510825598663,  0.7754729357942093, 0.38627346958246567};
  double r6[] = {0.6587345941106802,  0.5663307597019008, 0.745982532957802,
                 0.13773676069735807, 0.9533060648383948, 0.07403065415172849,
                 0.0414376470146659,  0.9207561759863303, 0.2081142211018856};
  double r7[] = {0.09324506812303357, 0.6466405359702434,  0.7851196750215607,
                 0.7098056789789724,  0.27310064284211233, 0.019730437467063933,
                 0.49286683872146697, 0.8537793525983003,  0.728719443104454};
  double r8[] = {0.3974080560351311,  0.18412236105584623, 0.4446678277855649,
                 0.30646594154281404, 0.564107542883322,   0.6844906363992634,
                 0.04644690011424013, 0.4670663137284522,  0.6521394395315507};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
    M1.matrix[1][j] = r1[j];
    M1.matrix[2][j] = r2[j];
    M1.matrix[3][j] = r3[j];
    M1.matrix[4][j] = r4[j];
    M1.matrix[5][j] = r5[j];
    M1.matrix[6][j] = r6[j];
    M1.matrix[7][j] = r7[j];
    M1.matrix[8][j] = r8[j];
  }

  double det = 0;
  double correct_det = -0.0806184778138818;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_OK);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_2) {
  int rows = 6, cols = 5;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.6040440883684846, 0.9344303029963308, 0.6729528645358748,
                 0.8119070481751057, 0.4178956185952789};
  double r1[] = {0.5576666861934546, 0.7067474155583295, 0.6778663347596174,
                 0.9877933596848548, 0.3087885286080334};
  double r2[] = {0.29267404531668284, 0.8953114468185106, 0.3249839421696482,
                 0.21413723330638046, 0.9803827855983704};
  double r3[] = {0.8856566199545549, 0.82865038265527, 0.6941892486520586,
                 0.43064826781821874, 0.4909883260015554};
  double r4[] = {0.7395544003364911, 0.7793245225773584, 0.6855557257373868,
                 0.17451460608487857, 0.5139189421126601};
  double r5[] = {0.07018604755556113, 0.8392425345633655, 0.4866553089566551,
                 0.2420388653842238, 0.18061736259273586};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
    M1.matrix[1][j] = r1[j];
    M1.matrix[2][j] = r2[j];
    M1.matrix[3][j] = r3[j];
    M1.matrix[4][j] = r4[j];
    M1.matrix[5][j] = r5[j];
  }

  double det = 0;
  double correct_det = 0;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_CALC_ERROR);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_3) {
  int rows = 1, cols = 1;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.25221326329352967};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
  }

  double det = 0;
  double correct_det = 0.25221326329352967;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_OK);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_4) {
  int rows = 5, cols = 5;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.3333414462627713, 0.37480478632510084, 0.14058330927305984,
                 0.18087659504072984, 0.1975375601574012};
  double r1[] = {0.4945297715476853, 0.12249968336331407, 0.053748650965932177,
                 0.9560676806684999, 0.8666655427538934};
  double r2[] = {0.5706838461415042, 0.5516037569942829, 0.6022048781619813,
                 0.4799042826499065, 0.0005211037366958937};
  double r3[] = {0.021505624502193954, 0.8244125217841675, 0.03285878580933521,
                 0.6981772120444231, 0.4157879074522899};
  double r4[] = {0.08294293351983295, 0.0817870011937516, 0.030392525961926542,
                 0.5394394547521995, 0.7896036704413918};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
    M1.matrix[1][j] = r1[j];
    M1.matrix[2][j] = r2[j];
    M1.matrix[3][j] = r3[j];
    M1.matrix[4][j] = r4[j];
  }

  double det = 0;
  double correct_det = -0.05002295238896294;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_OK);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_5) {
  int rows = 5, cols = 5;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.23325947607330966, 0.14300274435390725, 0.8712369890596394,
                 0.8933939288351637, 0.3556725210868521};
  double r1[] = {0.38159165649456483, 0.3501596705407055, 0.47600311438092857,
                 0.3426873917354817, 0.35040542613474424};
  double r2[] = {0.26527410862688816, 0.13100688016112239, 0.4267700750339172,
                 0.26332841179784827, 0.512684015232898};
  double r3[] = {0.8164909642324143, 0.7745301450976204, 0.4559839903836591,
                 0.12974593159924042, 0.3268116691089158};
  double r4[] = {0.034046988277617096, 0.8320343414561229, 0.8291627468208641,
                 0.20108769757778477, 0.31407905771161226};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
    M1.matrix[1][j] = r1[j];
    M1.matrix[2][j] = r2[j];
    M1.matrix[3][j] = r3[j];
    M1.matrix[4][j] = r4[j];
  }

  double det = 0;
  double correct_det = 0.008502838369510957;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_OK);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_6) {
  int rows = 1, cols = 7;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.047100821291088724, 0.10652275010452039,
                 0.036494911788591766, 0.453897112058275,
                 0.07600325243992279,  0.07423261951549831,
                 0.47787272689394267};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
  }

  double det = 0;
  double correct_det = 0;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_CALC_ERROR);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_7) {
  int rows = 8, cols = 8;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.037540901357332235, 0.1735147791508721, 0.9435308945071967,
                 0.3122610798446055,   0.8517406540010345, 0.6060343821107096,
                 0.24708693071298415,  0.7729118217790236};
  double r1[] = {0.7765514054590515,  0.674317378637629,   0.16428500979899685,
                 0.4439347747399969,  0.39191146689366885, 0.3870680918503505,
                 0.40607095947863536, 0.4350255885592238};
  double r2[] = {0.9504209891204292,  0.7240536919248312, 0.010060083043199164,
                 0.48020383420835366, 0.6395186276798609, 0.3478156692341938,
                 0.8468349719305555,  0.12548522681036833};
  double r3[] = {0.030079935860859552, 0.7002455997007,    0.49306834159040513,
                 0.943663871285659,    0.2642478685506462, 0.7804044632016531,
                 0.5600828530862885,   0.5815619937981591};
  double r4[] = {0.10486928243333327, 0.34046181781096296, 0.27056057830072844,
                 0.5887092322949407,  0.19557327908784505, 0.18190953109902608,
                 0.5753650509161221,  0.6136121173377539};
  double r5[] = {0.46927909811686186, 0.3543209490374135, 0.4613853568084637,
                 0.3212620134426588,  0.7116159029183585, 0.3216215957641758,
                 0.9428435207803748,  0.4939877077867548};
  double r6[] = {0.61857397256224,   0.053030990288620794, 0.6525380094290143,
                 0.6707474622714877, 0.04807665171979947,  0.3314422411890048,
                 0.6050071414040613, 0.028233534459450427};
  double r7[] = {0.2682230242487528,  0.19441836837840465, 0.8253442575232092,
                 0.24071500771610743, 0.7175181079960085,  0.43212190739922784,
                 0.04366435203774066, 0.11416950673599302};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
    M1.matrix[1][j] = r1[j];
    M1.matrix[2][j] = r2[j];
    M1.matrix[3][j] = r3[j];
    M1.matrix[4][j] = r4[j];
    M1.matrix[5][j] = r5[j];
    M1.matrix[6][j] = r6[j];
    M1.matrix[7][j] = r7[j];
  }

  double det = 0;
  double correct_det = 0.011673062453285693;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_OK);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_8) {
  int rows = 6, cols = 6;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.06714285348949778, 0.5610290656530854, 0.5542921819581434,
                 0.31031838028392156, 0.8634500642184697, 0.6964938331568655};
  double r1[] = {0.7912935238004076, 0.043281627548552914, 0.39162054932632806,
                 0.6389558366302203, 0.4501487529958462,   0.6633096648907141};
  double r2[] = {0.03325209511313698, 0.44562772554527497, 0.12717084705271187,
                 0.10644291016337659, 0.04867263452055859, 0.1711779768079431};
  double r3[] = {0.8557415877870969, 0.0407617514918277, 0.810045346403384,
                 0.9147449138870624, 0.7184104841598145, 0.6923304893806527};
  double r4[] = {0.7179008974958534, 0.2509177311918722,  0.5506117360205512,
                 0.6720719159412218, 0.45916016112039015, 0.9101526888706843};
  double r5[] = {0.6926779050182973, 0.675122284840622,  0.5774622195854452,
                 0.811123499968271,  0.1388287846404117, 0.5706982186713868};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
    M1.matrix[1][j] = r1[j];
    M1.matrix[2][j] = r2[j];
    M1.matrix[3][j] = r3[j];
    M1.matrix[4][j] = r4[j];
    M1.matrix[5][j] = r5[j];
  }

  double det = 0;
  double correct_det = -0.0014078337943211575;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_OK);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_9) {
  int rows = 5, cols = 5;
  matrix_t M1 = {0};
  scp_create_matrix(rows, cols, &M1);
  double r0[] = {0.009611485775960715, 0.6851900214242267, 0.4011897396150713,
                 0.5868013235133138, 0.3979260130415254};
  double r1[] = {0.11223065138839194, 0.8740615294016914, 0.6677489728998356,
                 0.7284972402005908, 0.3359392967723325};
  double r2[] = {0.09739846692068721, 0.29780717310639004, 0.443322973160999,
                 0.47819942433740137, 0.06940989949590426};
  double r3[] = {0.37199661778588367, 0.7683502069169816, 0.6872536630134283,
                 0.935204845026273, 0.4660755173307065};
  double r4[] = {0.638338052858482, 0.25988063440515985, 0.8380497362052093,
                 0.5627630842379531, 0.4913483564751132};

  for (int j = 0; j < cols; j++) {
    M1.matrix[0][j] = r0[j];
    M1.matrix[1][j] = r1[j];
    M1.matrix[2][j] = r2[j];
    M1.matrix[3][j] = r3[j];
    M1.matrix[4][j] = r4[j];
  }

  double det = 0;
  double correct_det = -0.006022441091945527;
  int res = scp_determinant(&M1, &det);
  ck_assert_double_eq_tol(det, correct_det, SCP_EPS);
  ck_assert_int_eq(res, SCP_OK);
  scp_remove_matrix(&M1);
}
END_TEST

START_TEST(scp_determinant_10) {
  ck_assert_int_eq(scp_determinant(NULL, NULL), SCP_ERROR);
}
END_TEST

START_TEST(scp_determinant_11) {
  double det = 0;
  INV_MATRIX
  ck_assert_int_eq(scp_determinant(&inv_matrix, &det), SCP_ERROR);
}
END_TEST

Suite *scp_determinant_tests(void) {
  Suite *s1 = suite_create(PRE_TEST_HEADER "SCP_DETERMINANT" POST_TEST_HEADER);
  TCase *tc1_1 = tcase_create("SCP_DETERMINANT");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, scp_determinant_0);
  tcase_add_test(tc1_1, scp_determinant_1);
  tcase_add_test(tc1_1, scp_determinant_2);
  tcase_add_test(tc1_1, scp_determinant_3);
  tcase_add_test(tc1_1, scp_determinant_4);
  tcase_add_test(tc1_1, scp_determinant_5);
  tcase_add_test(tc1_1, scp_determinant_6);
  tcase_add_test(tc1_1, scp_determinant_7);
  tcase_add_test(tc1_1, scp_determinant_8);
  tcase_add_test(tc1_1, scp_determinant_9);
  tcase_add_test(tc1_1, scp_determinant_10);
  tcase_add_test(tc1_1, scp_determinant_11);

  return s1;
}
